Repository williamchong256/immersive-sleep, pull requests merged in 2021-01, with the labels that each got.

#41 Format README to conform to Markdown style
  README.md
Labels: documentation

#40 Danny
  README.md
  hardware/MAX30100/findings.txt
  hardware/MAX30100/schematic.png
  hardware/code/MAX30100_wifi_interfacing.PNG
  hardware/code/MAX30100_wifi_interfacing.ino
  hardware/code/pulse_sensor_basic.ino
  hardware/pulse_sensor/pulse_sensor_findings.txt
  hardware/pulse_sensor/pulse_sensor_schematic.png
Labels: enhancement

#45 Styled-Components Integration
  frontend/App.jsx
  frontend/Themes.jsx
  frontend/dataTab.jsx
  frontend/detailedData.jsx
  frontend/homeTabs.jsx
  frontend/settingsTab.jsx
  frontend/style.js
Labels: enhancement

#46 Implement StackNavigator in Ambiance Tab
  frontend/AmbianceTab.jsx
  frontend/App.jsx
  frontend/homeTabs.jsx
Labels: enhancement

#42 Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#51 Store comments into database
  frontend/detailedData.jsx
  frontend/package.json
Labels: enhancement

#54 Set the header of each detailed data page to its date
  frontend/detailedData.jsx
Labels: enhancement

#65 Reverse direction of sample data
  frontend/homeTabs.jsx
  frontend/sampleData.json
Labels: bug

#68 Modify app.json for Android keyboard layout
  frontend/app.json
Labels: bug
