Repository williamchong256/immersive-sleep, pull requests merged in 2021-02, with the labels that each got.

#74 reorganized layout, added preview, changed background
  frontend/AmbianceTab.jsx
  frontend/Lighting.jsx
  frontend/Themes.jsx
Labels: enhancement

#70 Moved code files to src/
  frontend/App.jsx
  frontend/src/AmbianceTab.jsx
  frontend/src/Lighting.jsx
  frontend/src/Themes.jsx
  frontend/src/backendTesting.jsx
  frontend/src/dataTab.jsx
  frontend/src/detailedData.jsx
  frontend/src/diagnosticsTab.jsx
  frontend/src/homeTabs.jsx
  frontend/src/sampleData.json
  frontend/src/settings/Goals.jsx
  frontend/src/settings/Notifications.jsx
  frontend/src/settings/Preferences.jsx
  frontend/src/settings/Profile.jsx
  frontend/src/settingsTab.jsx
  frontend/src/startTab.jsx
  frontend/src/style.js
Labels: help wanted

#94 Update README with AWS setup instructions
  README.md
Labels: aws, documentation
